# Author: Nick Saika <n@nesv.ca>
#
# This theme is a port of naysayer-theme.el:
#    https://github.com/nickav/naysayer-theme.el

# "ui.background"        = { bg = "bg" }
"ui.text"                = "beige"
"ui.linenr"              = { fg = "line-fg" }
"ui.linenr.selected"     = { bg = "highlight-line", fg = "line-fg", modifiers = ["bold"] }
"ui.selection"           = { bg = "line-fg" }
"ui.cursorline"          = { bg = "highlight-line" }
"ui.statusline"          = { fg = "bg", bg = "beige" }
"ui.statusline.inactive" = { fg = "beige", bg = "bg" }
"ui.virtual.ruler"       = { bg = "line-fg" }
"ui.cursor.match"        = { bg = "line-fg", fg = "lime" }
"ui.cursor"              = { bg = "cyan", fg = "bg" }
"ui.cursor.primary"      = { bg = "lime", fg = "bg" }
"ui.highlight.frameline" = { bg = "#da8581" }
"ui.help"                = { fg = "beige", bg = "bg" }
"ui.popup"               = { bg = "highlight-line" }
"ui.menu"                = { fg = "beige", bg = "bg" }
"ui.menu.selected"       = { modifiers = ["reversed"] }
"ui.window"              = { bg = "bg" }
"ui.bufferline"          = { fg = "beige" }
"ui.bufferline.active"   = { modifiers = ["reversed"] }
"ui.gutter.selected"     = { bg = "highlight-line" }
"ui.highlight"           = { bg = "highlight-line" }
"ui.virtual.whitespace"  = { fg = "line-fg" }
"diagnostic"             = { underline = { style = "line", color = "cyan" } }

# Scopes: Syntax Highlighting.
"info"                   = "cyan"
"warning"                = "beige"
"error"                  = "red"
"attribute"              = "beige"
"type"                   = "lime"
"type.builtin"           = "lime"
"constructor"            = "lime"
"constant"               = "cyan"
"string"                 = "strong_cyan"
"comment"                = "green"
"variable"               = "blue"
"variable.builtin"       = "lime"
"punctuation"            = "beige"
"keyword"                = "white"
"function"               = "white"
"tag.builtin"            = "lime"
"markup.bold"            = { modifiers = ["bold"]   }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"diff.plus"              = { fg = "green" }
"diff.minus"             = { fg = "red" }
"diff.delta"             = { fg = "blue" }

[palette]
bg                       = "#062329"
highlight-line           = "#0b3335"
line-fg                  = "#126367"
red                      = "#f92672"
white                    = "#ffffff"
beige                    = "#d1b897"
green                    = "#44b340"
lime                     = "#8cde94" 
blue                     = "#c1d1e3"
cyan                     = "#7ad0c6"
strong_cyan              = "#2ec09c"
