"keyword" = "blue0"
"type"    = "magenta0"
"string"  = "red0"
"comment" = "gray3"
# function = {modifiers = ["bold"]}

"markup.heading"       = "blue0"
"markup.list"          = "gray3"
"markup.bold"          = { modifiers = ["bold"] }
"markup.italic"        = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url"      = "blue0"

# "ui.background"    = { bg = "white0" }
"ui.linenr.selected" = "black0"

"ui.statusline"          = { fg = "black0", bg = "gray2" }
"ui.statusline.inactive" = { fg = "gray3", bg = "gray0" }
"ui.statusline.normal"   = { fg = "black0" }
"ui.statusline.insert"   = { fg = "blue0" }
"ui.statusline.select"   = { fg = "magenta0" }

"ui.popup"      = { bg = "gray0" }
"ui.window"     = "gray3"
"ui.help"       = { bg = "gray0" }
"ui.gutter"     = { bg = "gray0", fg = "gray3" }
"ui.text"       = "black0"
"ui.text.focus" = { bg = "blue1" }

"ui.selection"         = { bg = "gray1" }
"ui.selection.primary" = { bg = "gray2" }

"ui.cursor"         = { fg = "white0", bg = "black0" }
"ui.cursor.primary" = { fg = "white0", bg = "gray3" }
"ui.cursor.match"   = { bg = "blue1" }

"ui.menu"          = { bg = "gray0" }
"ui.menu.selected" = { bg = "blue1" }
"ui.menu.scroll"   = { fg = "gray3", bg = "blue1" }

error   = { fg = "red0", modifiers = ["underlined"] }
warning = { fg = "yellow0", modifiers = ["underlined"] }
info    = { fg = "cyan0", modifiers = ["underlined"] }
hint    = { fg = "gray3", modifiers = ["underlined"] }

"diagnostic.error"   = { bg = "red1" }
"diagnostic.warning" = { bg = "yellow1" }
"diagnostic.info"    = { bg = "cyan1" }
"diagnostic.hint"    = { bg = "gray3" }

[palette]
white0   = "#ffffff"
gray0    = "#f2f2f2"
gray1    = "#e0e0e0"
gray2    = "#c8c8c8"
gray3    = "#595959"
black0   = "#000000"

red0     = "#8b475d"
red1     = "#E6C1CC"
yellow0  = "#A68149"
yellow1  = "#E6D7C1"
cyan0    = "#3B8787"
cyan1    = "#9FD1D1"
blue0    = "#354fcf"
blue1    = "#B3C9FF"
magenta0 = "#551A8B"
